import "./js/custom-action-steps.js";
import "./js/custom-action-buffs.js";
import "./js/key-panel-fix.js";
import "./js/custom-bgm.js";
import "./js/custom-combat-conditions.js";
import "./js/custom-map-sounds.js";
import "./js/custom-map-styles.js";
sc.PARTY_OPTIONS.push("Hexacast1");
sc.PARTY_OPTIONS.push("Hexacast2");
sc.PARTY_OPTIONS.push("Hexacast3");